import embaralharAlternativas from "../../../utils/embaralharPerguntas";

export const perguntasDireitoConstitucional = embaralharAlternativas([
  {
    pergunta: "Qual é o ano de promulgação da atual Constituição Federal do Brasil?",
    opcoes: ["1985", "1986", "1987", "1988"],
    correta: 3,
  },
  {
    pergunta: "Qual dos seguintes é fundamento da República Federativa do Brasil segundo o art. 1º da Constituição?",
    opcoes: ["Democracia", "Soberania", "Valorização do trabalho", "Pluralismo político"],
    correta: 1,
  },
  {
    pergunta: "A forma de Estado adotada pela Constituição brasileira é:",
    opcoes: ["Confederação", "União", "Federação", "Província autônoma"],
    correta: 2,
  },
  {
    pergunta: "O princípio da dignidade da pessoa humana está previsto no artigo:",
    opcoes: ["1º", "3º", "5º", "37º"],
    correta: 1,
  },
  {
    pergunta: "Segundo a CF/88, a República Federativa do Brasil rege-se nas suas relações internas e externas pelos princípios da: igualdade, liberdade, cidadania e:",
    opcoes: ["Segurança Pública", "Soberania", "Jurisdicionalidade", "Eficiência"],
    correta: 1,
  },
  {
    pergunta: "O Poder Legislativo no âmbito federal é exercido pelo(a):",
    opcoes: ["Presidente da República e Ministros", "Congresso Nacional", "Supremo Tribunal Federal", "Assembléia Geral"],
    correta: 1,
  },
  {
    pergunta: "O regime político adotado pela Constituição é o da:",
    opcoes: ["Monarquia Constitucional", "Democracia Representativa e Participativa", "Autoritarismo Iluminado", "Teocracia Popular"],
    correta: 1,
  },
  {
    pergunta: "É correto afirmar que a segurança pública, segundo a Constituição, é dever: do Estado, direito e:",
    opcoes: ["Garantia de todos", "Serviço exclusivo da União", "Ato discricionário", "Função de cooperação entre os entes federados"],
    correta: 3,
  },
  {
    pergunta: "A Constituição Federal pode ser modificada mediante emenda, observando-se suas cláusulas pétreas. Qual dos temas a seguir é considerado cláusula pétrea?",
    opcoes: ["Direito de greve dos servidores públicos", "Forma federativa de Estado", "Regime de previdência complementar", "Competência legislativa dos Estados"],
    correta: 1,
  },
  {
    pergunta: "O controle de constitucionalidade realizado pelo(a) ____-‐ é via defesa dos direitos e garantias fundamentais.",
    opcoes: ["Tribunal de Contas da União", "Supremo Tribunal Federal", "Assembleia Legislativa Estadual", "Procurador-Geral da República"],
    correta: 1,
  },
  {
    pergunta: "Conforme a CF/88, os direitos sociais não abrangem:",
    opcoes: ["Educação", "Trabalho", "Propriedade", "Saúde"],
    correta: 2,
  },
  {
    pergunta: "Na Constituição, a separação dos Poderes implica que: o Poder Executivo não exerce funções típicas do Legislativo e o Poder Legislativo não exerce funções típicas do:",
    opcoes: ["Judiciário", "Ministério Público", "Tribunal de Contas", "Estado-Maior das Forças Armadas"],
    correta: 0,
  },
  {
    pergunta: "O direito à informação como direito fundamental está previsto no artigo:",
    opcoes: ["5º", "37º", "220", "196"],
    correta: 2,
  },
  {
    pergunta: "O princípio da supremacia do interesse público sobre o privado está previsto na Constituição para a administração pública no art. 37. Qual outro princípio está lá presente?",
    opcoes: ["Eficiência", "Partidarismo", "Sigilo", "Rentabilidade"],
    correta: 0,
  },
  {
    pergunta: "No âmbito do Poder Executivo federal, quem detém competência para nomear Ministros de Estado?",
    opcoes: ["Senado Federal", "Presidente da República", "Câmara dos Deputados", "Assembléia Nacional"],
    correta: 1,
  },
  {
    pergunta: "Os entes federados da República Federativa do Brasil não são:",
    opcoes: ["União", "Estados", "Municípios", "Províncias"],
    correta: 3,
  },
  {
    pergunta: "Conforme a Constituição, a iniciativa popular para projeto de lei na esfera federal exige o mínimo de quantas assinaturas de eleitores?",
    opcoes: ["0,1% do eleitorado nacional", "1% do eleitorado nacional", "0,5% do eleitorado nacional", "2% do eleitorado nacional"],
    correta: 0,
  },
  {
    pergunta: "O mandado de injunção destina-se a:",
    opcoes: [
      "Suspender execução de lei inconstitucional",
      "Garantir a execução de norma regulamentadora que falta",
      "Intervir em Estado que descumpre Constituição",
      "Fiscalizar Tribunal de Contas",
    ],
    correta: 1,
  },
  {
    pergunta: "No sistema federativo brasileiro, os Estados têm o poder de promover: a) polícia judiciária, b) polícia civil, c) polícia militar, conforme sua competência. Isso decorre da:",
    opcoes: ["Forma de Estado", "Soberania", "Autonomia dos Estados", "Competência supranacional"],
    correta: 2,
  },
  {
    pergunta: "O princípio da razoável duração do processo e os meios que garantem a eficiência são direitos assegurados no art. 5º, inciso:",
    opcoes: ["LXXVIII", "LV", "LX", "XXXVI"],
    correta: 0,
  },
  {
    pergunta: "A Constituição prevê que a lei penal não pode retroagir salvo para beneficiar o réu. Esse princípio é denominado:",
    opcoes: ["Irretroatividade da lei penal mais severa", "Legalidade absoluta", "Presunção de inocência", "Responsabilidade subjetiva"],
    correta: 0,
  },
  {
    pergunta: "O Brasil adota o Poder Presidencialista, isto é, o Presidente da República acumula papel de Chefe de Estado e de:",
    opcoes: ["Chefe do Poder Judiciário", "Chefe do Poder Legislativo", "Chefe de Governo", "Comandante em Chefe Parlamentar"],
    correta: 2,
  },
  {
    pergunta: "No âmbito da administração pública, o concurso público é exigido para a investidura em cargo público, ressalvadas as nomeações de natureza:",
    opcoes: ["Política", "Confiança e chefia", "Honorária e temporária", "Militar e religiosa"],
    correta: 1,
  },{ pergunta: "Em que ano foi promulgada a Constituição Federal?", opcoes: ["1986", "1988", "1990", "1992"], correta: 1 },
  { pergunta: "Qual é o princípio fundamental da Constituição?", opcoes: ["Liberdade", "Igualdade", "Soberania", "Separação de Poderes"], correta: 2 },
  { pergunta: "Qual é a forma de governo do Brasil?", opcoes: ["Monarquia", "República", "Ditadura", "Oligarquia"], correta: 1 },
  { pergunta: "Qual é o regime de governo previsto na Constituição?", opcoes: ["Parlamentarismo", "Presidencialismo", "Monarquia Constitucional", "Semi-presidencialismo"], correta: 1 },
  { pergunta: "Qual dos poderes é responsável por elaborar leis?", opcoes: ["Executivo", "Legislativo", "Judiciário", "Ministério Público"], correta: 1 },
  { pergunta: "O direito de votar é garantido a cidadãos a partir de qual idade?", opcoes: ["16 anos", "18 anos", "21 anos", "14 anos"], correta: 0 },
  { pergunta: "A Constituição garante direito de reunião, desde que:", opcoes: ["Com registro policial", "Pacífica e sem armas", "Autorizada pelo Executivo", "Sempre em locais públicos"], correta: 1 },
  { pergunta: "Qual é o documento que estabelece direitos e deveres fundamentais?", opcoes: ["Código Civil", "Constituição Federal", "Lei de Execução Penal", "Estatuto da Polícia"], correta: 1 },
  { pergunta: "O voto no Brasil é:", opcoes: ["Opcional para todos", "Obrigatório para maiores de 18 e facultativo para 16 e 17 anos", "Sempre obrigatório", "Nunca obrigatório"], correta: 1 },
  { pergunta: "O princípio da separação dos poderes garante:", opcoes: ["Poder absoluto do Executivo", "Equilíbrio entre Legislativo, Executivo e Judiciário", "Supremacia do Judiciário", "Supremacia do Legislativo"], correta: 1 },
  { pergunta: "Direitos sociais incluem:", opcoes: ["Saúde, educação, trabalho e previdência", "Somente saúde", "Somente trabalho", "Nenhum direito"], correta: 0 },
  { pergunta: "Quem pode propor emenda à Constituição?", opcoes: ["Presidente da República, Congresso e cidadãos com iniciativa popular", "Apenas o Presidente", "Apenas o Congresso", "Somente o Judiciário"], correta: 0 },
  { pergunta: "O mandado de segurança é utilizado para proteger:", opcoes: ["Direitos líquidos e certos", "Direitos sociais", "Direitos políticos", "Direitos penais"], correta: 0 },
  { pergunta: "O habeas corpus protege:", opcoes: ["Liberdade de locomoção", "Patrimônio", "Trabalho", "Educação"], correta: 0 },
  { pergunta: "Qual é a hierarquia das normas no Brasil?", opcoes: ["Lei ordinária > Constituição > Decretos", "Constituição > Emendas > Leis", "Decretos > Leis > Constituição", "Código Penal > Constituição > Lei"], correta: 1 },
  { pergunta: "A Constituição Federal estabelece que o Brasil é:", opcoes: ["Estado laico", "Estado religioso", "Estado militar", "Estado monárquico"], correta: 0 },
  { pergunta: "A inviolabilidade da intimidade e da vida privada é garantida em qual artigo?", opcoes: ["Art. 1", "Art. 5", "Art. 7", "Art. 10"], correta: 1 },
  { pergunta: "O direito à propriedade é garantido desde que:", opcoes: ["Respeite sua função social", "Não haja impostos", "Apenas em áreas urbanas", "Sem limitações"], correta: 0 },
  { pergunta: "O SUS (Sistema Único de Saúde) é garantido por qual artigo?", opcoes: ["Art. 196", "Art. 150", "Art. 5", "Art. 100"], correta: 0 },
  { pergunta: "O acesso à educação é dever do:", opcoes: ["Estado, família e sociedade", "Só do Estado", "Só da família", "Só da sociedade"], correta: 0 },
  { pergunta: "O princípio da legalidade significa:", opcoes: ["Só pode fazer o que a lei permite", "Pode fazer tudo", "Pode agir sem lei", "Lei não importa"], correta: 0 },
  { pergunta: "A liberdade de expressão é garantida:", opcoes: ["Com limites legais", "Sem limites", "Somente para políticos", "Somente na imprensa"], correta: 0 },
  { pergunta: "O direito de petição garante:", opcoes: ["Requerer providências a autoridades", "Receber salário", "Não ser preso", "Ter arma"], correta: 0 },
  { pergunta: "O princípio da dignidade da pessoa humana está no:", opcoes: ["Art. 1º", "Art. 5º", "Art. 7º", "Art. 10º"], correta: 0 },
  { pergunta: "A igualdade perante a lei significa:", opcoes: ["Todos têm mesmos direitos e deveres", "Uns têm privilégios", "Apenas alguns direitos", "Só para servidores"], correta: 0 },
  { pergunta: "Direitos trabalhistas são previstos em:", opcoes: ["CF, CLT e leis complementares", "CF apenas", "CLT apenas", "Código Penal"], correta: 0 },
  { pergunta: "A Constituição prevê a defesa do consumidor em qual artigo?", opcoes: ["Art. 5º", "Art. 170", "Art. 12", "Art. 100"], correta: 1 },
  { pergunta: "O voto secreto é garantido para:", opcoes: ["Eleitores", "Candidatos", "Servidores", "Juízes"], correta: 0 },
  { pergunta: "O princípio da publicidade dos atos públicos visa:", opcoes: ["Transparência", "Sigilo total", "Somente judiciário", "Somente executivo"], correta: 0 },
  { pergunta: "A liberdade religiosa é garantida desde que:", opcoes: ["Não viole direitos de terceiros", "Sempre sem restrições", "Apenas no culto", "Só para líderes"], correta: 0 },
  {
    pergunta: "O direito de ir e vir está garantido na Constituição e só pode ser restringido por meio:",
    opcoes: [
      "Lei complementar",
      "Lei ordinária",
      "Decreto",
      "Ato administrativo",
    ],
    correta: 0,
  },
  {
    pergunta: "Qual instrumento constitucional assegura o cumprimento da constituição por meio da ação direta de inconstitucionalidade por omissão?",
    opcoes: ["ADI", "ADC", "ADO", "ADI/ADO"],
    correta: 2,
  },
  {
    pergunta: "O princípio da legalidade, estritamente no âmbito administrativo, está previsto no art. 37. Esse princípio determina que:",
    opcoes: ["O agente público só faz o que a lei permitir", "O agente público pode agir por analogia", "O agente público pode agir conforme normativos internos", "O agente público tem liberdade para decidir"],
    correta: 0,
  },
  {
    pergunta: "O Poder Judiciário no regime constitucional deve exercer a jurisdição com base nos princípios da inafastabilidade da jurisdição e:",
    opcoes: ["Publicidade dos atos processuais", "Duplo grau de jurisdição", "Celeridade e economia processual", "Autonomia funcional"],
    correta: 2,
  },
  {
    pergunta: "A competência para legislar sobre estabelecimentos penais e medidas de segurança cabe a:",
    opcoes: ["União e Estados", "Estados e Municípios", "Municípios", "União exclusiva"],
    correta: 0,
  },
  {
    pergunta: "A modificação da Constituição Federal ocorre por meio de emenda. Uma Proposta de Emenda à Constituição (PEC) exige a aprovação de no mínimo:",
    opcoes: [
      "Metade dos membros de cada Casa do Congresso Nacional",
      "Dois terços dos membros de cada Casa em dois turnos",
      "Três quintos dos membros da Câmara dos Deputados em um turno",
      "Unanimidade dos membros do Senado Federal",
    ],
    correta: 1,
  },
]);
