import embaralharAlternativas from "../../../utils/embaralharPerguntas";

export const perguntasDireitoAdministrativo = embaralharAlternativas([
  { pergunta: "O que caracteriza a Administração Pública direta?", opcoes: ["Órgãos que integram a estrutura do Estado", "Empresas privadas contratadas pelo Estado", "Organizações não governamentais", "Entidades internacionais"], correta: 0 },
  { pergunta: "A Administração Pública indireta é composta por:", opcoes: ["Autarquias, fundações, empresas públicas e sociedades de economia mista", "Ministérios e secretarias", "Partidos políticos", "ONGs"], correta: 0 },
  { pergunta: "O princípio da legalidade significa:", opcoes: ["A Administração só pode agir conforme a lei", "A lei deve seguir a vontade do administrador", "Tudo é permitido", "Há liberdade total para os agentes"], correta: 0 },
  { pergunta: "O princípio da impessoalidade garante:", opcoes: ["Que atos administrativos não beneficiem pessoas específicas", "A liberdade de contratar", "Nomeações políticas livres", "Punição sem processo"], correta: 0 },
  { pergunta: "O princípio da moralidade administrativa exige:", opcoes: ["Atuação ética e conforme a lei", "Somente eficiência", "Exclusivamente lucro", "Obediência cega a superiores"], correta: 0 },
  { pergunta: "O princípio da publicidade implica:", opcoes: ["Transparência dos atos administrativos", "Sigilo absoluto", "Divulgação apenas interna", "Liberdade de imprensa"], correta: 0 },
  { pergunta: "O que é a Administração Pública direta?", opcoes: ["Órgãos que integram a estrutura do Estado", "Empresas públicas", "Fundações privadas", "ONGs"], correta: 0 },
  { pergunta: "A Administração Pública indireta compreende:", opcoes: ["Autarquias, fundações públicas, empresas públicas e sociedades de economia mista", "Ministérios", "Prefeituras apenas", "Institutos privados"], correta: 0 },
  { pergunta: "Qual é a diferença entre poderes da Administração e poderes dos governantes?", opcoes: ["Poderes da Administração são previstos em lei e impessoais", "Poderes dos governantes são absolutos", "Não há diferença", "Os poderes administrativos são discricionários"], correta: 0 },
  { pergunta: "O que caracteriza o ato administrativo complexo?", opcoes: ["Depende de manifestação conjunta de dois ou mais órgãos", "É assinado por uma pessoa apenas", "É sempre normativo", "Não produz efeitos jurídicos"], correta: 0 },
  { pergunta: "O que caracteriza o ato administrativo composto?", opcoes: ["Um órgão subordina-se a outro para sua formação", "É produzido por entidades privadas", "Não precisa de assinatura", "É revogado automaticamente"], correta: 0 },
  { pergunta: "O que é o ato administrativo vinculado?", opcoes: ["A Administração não possui liberdade de escolha", "Pode ser alterado a qualquer momento", "Depende de decreto presidencial", "É meramente sugestivo"], correta: 0 },
  { pergunta: "O que é o ato administrativo discricionário?", opcoes: ["A Administração possui margem de escolha dentro da lei", "Pode descumprir a lei", "É sempre ilegal", "Não possui efeitos jurídicos"], correta: 0 },
  { pergunta: "Quais são os elementos do ato administrativo?", opcoes: ["Competência, finalidade, forma, motivo e objeto", "Assinatura e carimbo apenas", "Apenas competência e objeto", "Apenas finalidade"], correta: 0 },
  { pergunta: "O que é um ato administrativo nulo?", opcoes: ["Aquele que possui vícios graves, tornando-o inexistente", "Aquele que pode ser convalidado", "Aquele que produz efeitos temporários", "Aquele que é revogado"], correta: 0 },
  { pergunta: "O que é um ato administrativo anulável?", opcoes: ["Aquele que possui vícios menos graves e pode ser convalidado", "Aquele que nunca produz efeitos", "Aquele que é ilegal e irrevogável", "Aquele que é obrigatório"], correta: 0 },
  { pergunta: "O controle judicial dos atos administrativos ocorre para:", opcoes: ["Verificar legalidade e proteger direitos", "Revisar mérito político", "Substituir gestores", "Modificar leis"], correta: 0 },
  { pergunta: "O princípio da autotutela permite:", opcoes: ["A Administração revisar seus próprios atos", "A Administração criar leis", "O juiz controlar atos administrativos", "O gestor punir sem processo"], correta: 0 },
  { pergunta: "O que é poder hierárquico?", opcoes: ["Organização, supervisão e delegação de competências", "Poder de legislar", "Poder de julgar criminalmente", "Liberdade total do gestor"], correta: 0 },
  { pergunta: "O poder disciplinar se aplica a:", opcoes: ["Servidores públicos e infrações funcionais", "Todos os cidadãos", "Empresas privadas", "Partidos políticos"], correta: 0 },
  { pergunta: "O que caracteriza o poder regulamentar?", opcoes: ["Complementa a lei por meio de decretos e regulamentos", "Cria leis", "Revoga constituição", "Disciplina partidos"], correta: 0 },
  { pergunta: "O que é poder de polícia?", opcoes: ["Limita direitos em benefício da coletividade", "Aumenta impostos", "Fiscaliza partidos políticos", "Executa ordens judiciais"], correta: 0 },
  { pergunta: "O que são contratos administrativos?", opcoes: ["Acordos firmados pela Administração seguindo normas legais", "Contratos entre particulares", "Acordos informais", "Atos meramente internos"], correta: 0 },
  { pergunta: "O que distingue contrato administrativo de contrato privado?", opcoes: ["Presença de cláusulas exorbitantes e sujeição a lei especial", "Valor do contrato", "Partes envolvidas apenas", "Prazo de execução"], correta: 0 },
  { pergunta: "O que caracteriza licitação inexigível?", opcoes: ["Quando há inviabilidade de competição", "Quando há muitos concorrentes", "Para qualquer obra pública", "Quando o contrato é pequeno"], correta: 0 },
  { pergunta: "O que caracteriza licitação dispensável?", opcoes: ["Situações previstas em lei como emergência ou guerra", "Sempre que houver concorrência", "Quando há mais de 5 propostas", "Para serviços contínuos"], correta: 0 },
  { pergunta: "O que é improbidade administrativa?", opcoes: ["Conduta ilícita de agente público que causa prejuízo à Administração", "Infração civil comum", "Atividade partidária ilegal", "Crime militar apenas"], correta: 0 },
  { pergunta: "O que é responsabilidade civil do Estado?", opcoes: ["Obrigação de reparar danos causados a terceiros", "Apenas punir servidores", "Responsabilidade criminal", "Responsabilidade moral"], correta: 0 },
  { pergunta: "O que é poder vinculado?", opcoes: ["Quando a lei determina exatamente como o ato deve ser praticado", "Quando o gestor tem liberdade total", "Quando não há lei", "Quando é discricionário"], correta: 0 },
  { pergunta: "O que caracteriza serviço público?", opcoes: ["Atividade de interesse coletivo, prestada direta ou indiretamente", "Atividade exclusivamente privada", "Serviço opcional", "Serviço sem regulação"], correta: 0 },
  { pergunta: "O que é controle interno da Administração?", opcoes: ["Fiscalização feita pela própria Administração", "Controle feito pelo Congresso", "Controle judicial", "Controle do cidadão"], correta: 0 },
  { pergunta: "O que é controle externo da Administração?", opcoes: ["Fiscalização realizada pelo Legislativo e Tribunais de Contas", "Controle interno apenas", "Apenas fiscalização judicial", "Controle de sindicatos"], correta: 0 },
  { pergunta: "O que são bens públicos dominicais?", opcoes: ["Bens pertencentes ao Estado mas não afetados a serviço público", "Bens privados", "Bens culturais", "Bens estaduais obrigatórios"], correta: 0 },
  { pergunta: "O que são bens públicos de uso especial?", opcoes: ["Bens destinados a fins específicos da Administração", "Bens livres", "Bens de particulares", "Bens patrimoniais"], correta: 0 },
  { pergunta: "O que são bens públicos de uso comum do povo?", opcoes: ["Bens disponíveis a todos, como praças e ruas", "Bens privados", "Bens administrativos internos", "Bens fiscais apenas"], correta: 0 },
  { pergunta: "O princípio da eficiência significa:", opcoes: ["Atuação da Administração com economia, rapidez e qualidade", "Aumento do gasto público", "Contratação de amigos", "Redução de pessoal sem critério"], correta: 0 },
  { pergunta: "O ato administrativo é:", opcoes: ["Manifestação unilateral da Administração que produz efeitos jurídicos", "Contrato entre particulares", "Lei aprovada pelo Congresso", "Sentença judicial"], correta: 0 },
  { pergunta: "A discricionariedade administrativa permite:", opcoes: ["Escolha dentro dos limites legais", "Liberdade total de agir", "Ignorar a lei", "Anular leis"], correta: 0 },
  { pergunta: "O controle da Administração Pública pode ser:", opcoes: ["Interno e externo", "Exclusivamente interno", "Exclusivamente externo", "Somente judicial"], correta: 0 },
  { pergunta: "O servidor público estatutário tem seu regime definido por:", opcoes: ["Lei específica", "Contrato particular", "Código Penal", "Regimento interno apenas"], correta: 0 },
  { pergunta: "O servidor celetista tem seu regime definido por:", opcoes: ["CLT", "Constituição Federal", "Regimento interno", "Código Civil"], correta: 0 },
  { pergunta: "Licitação tem por objetivo:", opcoes: ["Assegurar igualdade e selecionar a proposta mais vantajosa", "Favorecer empresas amigas", "Reduzir impostos", "Garantir lucro do governo"], correta: 0 },
  { pergunta: "É dispensável a licitação quando:", opcoes: ["Situações previstas em lei, como guerra ou emergência", "Sempre que houver mais de 3 concorrentes", "Para contratação de qualquer serviço", "Somente para obras públicas"], correta: 0 },
  { pergunta: "É inexigível a licitação quando:", opcoes: ["Há inviabilidade de competição, como fornecedor exclusivo", "O contrato é grande", "O valor é baixo", "O gestor desejar"], correta: 0 },
  { pergunta: "O regime jurídico-administrativo é:", opcoes: ["Conjunto de normas que regulam a atuação do Estado", "Somente aplicável a contratos", "Exclusivo para servidores", "Regime penal"], correta: 0 },
  { pergunta: "O poder hierárquico permite:", opcoes: ["Organizar e supervisionar a Administração", "Aumentar salário", "Elaborar leis", "Aplicar justiça criminal"], correta: 0 },
  { pergunta: "O poder disciplinar permite:", opcoes: ["Punir infrações funcionais", "Modificar leis", "Suspender concursos", "Aumentar impostos"], correta: 0 },
  { pergunta: "O poder regulamentar permite:", opcoes: ["Complementar a lei com decretos e regulamentos", "Alterar a Constituição", "Revogar leis estaduais", "Punir servidores"], correta: 0 },
  { pergunta: "O poder de polícia consiste em:", opcoes: ["Limitar direitos em benefício da coletividade", "Criar leis penais", "Administrar contratos privados", "Aplicar multas arbitrárias"], correta: 0 },
  { pergunta: "O contrato administrativo é regido por:", opcoes: ["Normas específicas da Administração", "Código Civil apenas", "CLT", "Código Penal"], correta: 0 },
  { pergunta: "O ato de improbidade administrativa pode gerar:", opcoes: ["Perda da função pública, ressarcimento e multa", "Suspensão de direitos políticos apenas", "Advertência verbal", "Nada"], correta: 0 },
  { pergunta: "O processo administrativo visa:", opcoes: ["Garantir o devido processo legal interno", "Aplicar leis penais", "Somente arrecadar tributos", "Reprimir opiniões"], correta: 0 },
  { pergunta: "O regime de bens públicos é classificado em:", opcoes: ["Bens de uso comum, de uso especial e dominicais", "Bens particulares apenas", "Bens culturais", "Bens tributários"], correta: 0 },
  { pergunta: "O controle interno é exercido por:", opcoes: ["Própria Administração", "Tribunal de Contas", "Judiciário", "Ministério Público"], correta: 0 },
  { pergunta: "O controle externo é realizado por:", opcoes: ["Tribunal de Contas e Congresso Nacional", "Diretores de escola", "Prefeitos", "Servidores"], correta: 0 },
  { pergunta: "O serviço público deve atender aos princípios de:", opcoes: ["Continuidade, eficiência, igualdade e universalidade", "Exclusividade, lucro e sigilo", "Apenas eficiência", "Nada"], correta: 0 },
  { pergunta: "As sanções administrativas incluem:", opcoes: ["Multa, suspensão e demissão", "Apenas advertência", "Prisões", "Apenas suspensão de direitos políticos"], correta: 0 },
  { pergunta: "A responsabilidade civil do Estado decorre de:", opcoes: ["Atos lícitos ou ilícitos que causem dano a terceiros", "Somente atos ilícitos penais", "Exclusivamente atos de servidores", "Decisões judiciais"], correta: 0 },
  { pergunta: "O serviço público pode ser prestado por:", opcoes: ["Administração direta ou indireta, ou delegação a terceiros", "Apenas empresas privadas", "Somente servidores estatutários", "ONGs"], correta: 0 },
]);
