import embaralharPerguntas from '../../../utils/embaralharPerguntas';

export const perguntasLeiExecucaoPenal = embaralharPerguntas([
  { pergunta: "A Lei de Execução Penal no Brasil é a de número:", opcoes: ["Lei 7.210/1984", "Lei 8.112/1990", "Lei 9.099/1995", "Lei 10.826/2003"], correta: 0 },
  { pergunta: "Qual o objetivo principal da Lei de Execução Penal?", opcoes: ["Reeducação e reintegração social do preso", "Punição sem ressocialização", "Somente vigilância do preso", "Controle financeiro do sistema prisional"], correta: 0 },
  { pergunta: "Segundo a LEP, o preso deve ter direito a:", opcoes: ["Alimentação, saúde, trabalho e educação", "Somente alimentação e saúde", "Apenas trabalho", "Nenhum direito específico"], correta: 0 },
  { pergunta: "A remição de pena ocorre através de:", opcoes: ["Trabalho ou estudo", "Reclamação administrativa", "Assistência jurídica", "Pagamento de multa"], correta: 0 },
  { pergunta: "O condenado em regime fechado tem direito à saída temporária:", opcoes: ["Sim, desde que cumpra requisitos legais", "Não, nunca", "Somente em regime aberto", "Somente para presos provisórios"], correta: 0 },
  { pergunta: "A assistência religiosa aos presos é:", opcoes: ["Obrigatória, respeitando a liberdade de crença", "Proibida", "Opcional, apenas católica", "Somente em datas comemorativas"], correta: 0 },
  { pergunta: "O juiz da execução penal é responsável por:", opcoes: ["Fiscalizar o cumprimento da pena", "Aplicar a pena inicial", "Executar prisão em flagrante", "Conceder benefícios de forma automática"], correta: 0 },
  { pergunta: "O preso provisório é aquele:", opcoes: ["Que ainda não teve condenação definitiva", "Que cumpre pena em regime aberto", "Que trabalha fora do presídio", "Que cumpre pena em regime fechado"], correta: 0 },
  { pergunta: "A LEP disciplina a execução da pena de prisão e:", opcoes: ["Medidas de segurança", "Multa administrativa", "Apenas vigilância policial", "Apenas benefícios fiscais"], correta: 0 },
  { pergunta: "O preso primário, segundo a LEP, é aquele:", opcoes: ["Cumprindo pena pela primeira vez", "Que reincidiu", "Detento provisório", "Que cumpre pena alternativa"], correta: 0 },
  { pergunta: "O direito à integridade física e moral do preso é:", opcoes: ["Garantido pela LEP", "Opcional", "Somente no regime aberto", "Não garantido"], correta: 0 },
  { pergunta: "O condenado tem direito à assistência material do Estado quando:", opcoes: ["Não possui meios de subsistência", "Sempre que solicitado", "Somente para menores de idade", "Nunca"], correta: 0 },
  { pergunta: "O trabalho do preso deve ser:", opcoes: ["Proporcional e remunerado", "Opcional e voluntário", "Obrigatório sem remuneração", "Restrito a atividades internas"], correta: 0 },
  { pergunta: "A assistência educacional visa:", opcoes: ["Preparar o preso para a reintegração social", "Somente ocupar o tempo do preso", "Apenas alfabetização", "Dar títulos acadêmicos"], correta: 0 },
  { pergunta: "O uso de sanções disciplinares dentro da prisão deve:", opcoes: ["Respeitar a dignidade do preso", "Ser arbitrário", "Ser público e punitivo", "Não ter critérios legais"], correta: 0 },
  { pergunta: "A execução da pena deve ser acompanhada por:", opcoes: ["Juiz da execução", "Promotor de justiça", "Defensor público apenas", "Agente penitenciário"], correta: 0 },
  { pergunta: "A saída temporária é destinada a:", opcoes: ["Presos no regime semiaberto", "Todos os condenados", "Apenas presos provisórios", "Apenas regime fechado"], correta: 0 },
  { pergunta: "O indulto ou comutação da pena é concedido por:", opcoes: ["Presidente da República", "Juiz da execução", "Ministro da Justiça", "Promotor de Justiça"], correta: 0 },
  { pergunta: "O recolhimento do preso a regime mais rigoroso ocorre quando:", opcoes: ["Houve falta grave", "Sempre no início da pena", "Por solicitação da família", "Nunca"], correta: 0 },
  { pergunta: "A assistência social deve incluir:", opcoes: ["Orientação familiar e comunitária", "Apenas pagamento de multas", "Somente fornecimento de alimentação", "Não é obrigatória"], correta: 0 },
  { pergunta: "A assistência religiosa deve ser:", opcoes: ["Livre e facultativa", "Obrigatória para todos", "Somente católica", "Proibida"], correta: 0 },
  { pergunta: "O regime aberto pode incluir:", opcoes: ["Trabalho externo durante o dia", "Permanência contínua no presídio", "Saídas temporárias ilimitadas", "Nenhum benefício"], correta: 0 },
  { pergunta: "O preso pode ser transferido de unidade prisional:", opcoes: ["Por necessidade administrativa ou segurança", "A qualquer momento, sem aviso", "Somente com autorização judicial", "Nunca"], correta: 0 },
  { pergunta: "O direito à saúde do preso é:", opcoes: ["Integral, preventiva e curativa", "Somente curativa", "Opcional", "Apenas emergencial"], correta: 0 },
  { pergunta: "O trabalho do condenado deve respeitar:", opcoes: ["Carga horária legal e condições de segurança", "Não há limites", "Apenas produtividade", "Não é regulamentado"], correta: 0 },
  { pergunta: "O recolhimento noturno obrigatório no regime semiaberto ocorre:", opcoes: ["Para garantir disciplina e segurança", "Para limitar liberdade irrestrita", "Nunca", "Só se solicitado pelo preso"], correta: 0 },
   { pergunta: "Qual é a lei que regula a execução penal no Brasil?", opcoes: ["Lei nº 7.210/1984", "Lei nº 11.343/2006", "Lei nº 8.069/1990", "Lei nº 12.850/2013"], correta: 0 },
  { pergunta: "A execução penal busca:", opcoes: ["Reeducar e reintegrar o condenado à sociedade", "Apenas punir", "Restringir direitos civis indefinidamente", "Evitar prisões preventivas"], correta: 0 },
  { pergunta: "O regime fechado é aplicado a:", opcoes: ["Condenados com pena maior de 8 anos ou crimes graves", "Todos os condenados", "Adolescentes infratores", "Crimes de menor potencial ofensivo"], correta: 0 },
  { pergunta: "O regime semiaberto permite:", opcoes: ["Trabalho externo durante o dia e recolhimento à noite", "Total liberdade sem restrições", "Cumprimento da pena em casa sem fiscalização", "Internação em unidade de segurança máxima"], correta: 0 },
  { pergunta: "O regime aberto é caracterizado por:", opcoes: ["Cumprimento da pena em residência com vigilância e horários determinados", "Trabalho em penitenciária apenas", "Internação em presídio fechado", "Liberdade total sem controle"], correta: 0 },
  { pergunta: "O livramento condicional é concedido quando:", opcoes: ["O condenado cumpre parte da pena e apresenta bom comportamento", "A pena já foi integralmente cumprida", "O condenado é menor de idade", "O condenado cometeu crime de baixo potencial ofensivo"], correta: 0 },
  { pergunta: "O indulto é:", opcoes: ["Perdão total ou parcial da pena concedido pelo presidente da República", "Redução automática da pena pelo juiz", "Remissão de pena apenas para menores", "Suspensão da pena sem perdão"], correta: 0 },
  { pergunta: "A progressão de regime depende de:", opcoes: ["Cumprimento mínimo da pena e bom comportamento", "Solicitação do preso apenas", "Idade do condenado", "Tipo de crime apenas"], correta: 0 },
  { pergunta: "O preso provisório deve ser separado de condenados?", opcoes: ["Sim, para garantir a presunção de inocência", "Não, todos juntos", "Apenas em casos de crimes violentos", "Somente se solicitado pelo preso"], correta: 0 },
  { pergunta: "A pena de multa é:", opcoes: ["Complementar à pena privativa de liberdade", "Aplicada isoladamente apenas para tráfico", "Não prevista na execução penal", "Exclusiva para menores de idade"], correta: 0 },
  { pergunta: "A remição de pena ocorre quando o preso:", opcoes: ["Trabalha ou estuda, reduzindo a pena", "Comete infração disciplinar", "Recebe visita de familiares", "Faz apenas atividades de lazer"], correta: 0 },
  { pergunta: "O diretor do estabelecimento penal tem como função:", opcoes: ["Administrar a unidade e fiscalizar a execução das penas", "Aplicar penas sem supervisão", "Determinar julgamentos", "Conceder liberdade condicional sem processo"], correta: 0 },
  { pergunta: "O preso tem direito a visitas e correspondências?", opcoes: ["Sim, respeitando normas de segurança", "Não, são proibidas", "Somente em feriados", "Apenas visitas de advogados"], correta: 0 },
  { pergunta: "O regime disciplinar diferenciado (RDD) é aplicado para:", opcoes: ["Presos de alta periculosidade", "Todos os presos provisórios", "Menores infratores", "Penas de multa"], correta: 0 },
  { pergunta: "A execução penal deve respeitar:", opcoes: ["A dignidade humana e os direitos fundamentais", "Somente a segurança da sociedade", "Apenas o cumprimento da pena", "A vontade do diretor do presídio"], correta: 0 },
  { pergunta: "A prisão domiciliar pode ser concedida em casos de:", opcoes: ["Doença grave, gestantes ou mães com filhos pequenos", "Todos os condenados", "Apenas idosos acima de 70 anos", "Infrações administrativas"], correta: 0 },
  { pergunta: "O direito ao trabalho do preso garante:", opcoes: ["Remição de pena e reintegração social", "Liberdade imediata", "Progressão automática de regime", "Auxílio financeiro externo"], correta: 0 },
  { pergunta: "O preso tem direito à assistência religiosa?", opcoes: ["Sim, independente da crença", "Não, é proibido", "Apenas no regime aberto", "Somente se solicitado por escrito"], correta: 0 },
  { pergunta: "O preso não pode ser transferido sem:", opcoes: ["Autorização judicial e comunicação formal", "Consentimento do diretor", "Solicitação de familiares", "Pedido ao Ministério Público"], correta: 0 },
  { pergunta: "A assistência jurídica ao preso é:", opcoes: ["Obrigatória, garantindo defesa e recursos", "Opcional", "Somente em casos de crimes graves", "Apenas mediante pagamento"], correta: 0 },
  { pergunta: "A execução penal prevê a criação de:", opcoes: ["Conselhos Penitenciários e Escolas Penitenciárias", "Tribunais de Execução Penal apenas", "Apenas presídios federais", "Delegacias especiais"], correta: 0 },
  { pergunta: "O preso tem direito a atendimento médico e odontológico?", opcoes: ["Sim, integralmente", "Não, apenas emergencial", "Somente se solicitar", "Somente em penitenciárias federais"], correta: 0 },
  { pergunta: "A assistência social ao preso visa:", opcoes: ["Reintegração e apoio à família", "Penas alternativas", "Evitar transferência de presos", "Somente trabalho remunerado"], correta: 0 },
  { pergunta: "A execução penal estabelece fiscalização de:", opcoes: ["Condições dos estabelecimentos e direitos dos presos", "Apenas progressão de regime", "Somente visitas", "Apenas remição de pena"], correta: 0 },
  { pergunta: "O preso tem direito à educação:", opcoes: ["Sim, para sua reabilitação", "Não, é opcional", "Somente leitura de livros", "Somente ensino religioso"], correta: 0 },
  { pergunta: "O juiz da execução penal pode:", opcoes: ["Decidir sobre progressão, livramento condicional e benefícios", "Conceder indulto sem critérios", "Determinar penas de multa isoladamente", "Remover presos sem processo"], correta: 0 },
  { pergunta: "O benefício do semiaberto deve ser acompanhado por:", opcoes: ["Monitoramento e fiscalização", "Liberdade irrestrita", "Visitas familiares apenas", "Assistência religiosa apenas"], correta: 0 },
  { pergunta: "O condenado que cumpre pena em regime fechado pode progredir para:", opcoes: ["Semiaberto, após cumprimento mínimo e bom comportamento", "Aberto automaticamente", "Liberdade total após 1 ano", "Não pode progredir"], correta: 0 },
  { pergunta: "A assistência à família do preso inclui:", opcoes: ["Suporte social e orientação", "Somente visitas", "Auxílio financeiro obrigatório", "Transferência automática"], correta: 0 },
  { pergunta: "O monitoramento eletrônico é utilizado para:", opcoes: ["Controlar cumprimento da pena em regime aberto ou semiaberto", "Punir o preso", "Exercer vigilância permanente", "Substituir trabalho"], correta: 0 },
  { pergunta: "O benefício da progressão de regime depende de:", opcoes: ["Bom comportamento e cumprimento mínimo da pena", "Solicitação do preso", "Decisão automática", "Apenas critério administrativo"], correta: 0 },
  { pergunta: "O condenado a penas restritivas de direitos cumpre:", opcoes: ["Medidas alternativas à prisão", "Apenas multa", "Reclusão obrigatória", "Trabalho forçado"], correta: 0 },
  { pergunta: "O preso provisório deve ser separado de presos condenados:", opcoes: ["Para respeitar presunção de inocência", "Não há separação", "Só se solicitado", "Dependendo do crime"], correta: 0 },
  { pergunta: "O benefício do trabalho externo é concedido a presos:", opcoes: ["No regime semiaberto e com bom comportamento", "Em regime fechado sempre", "Somente provisórios", "Nunca"], correta: 0 },
  { pergunta: "A assistência jurídica gratuita é garantida:", opcoes: ["Para quem não pode pagar defensor particular", "Opcional", "Somente durante julgamento", "Nunca"], correta: 0 },
  { pergunta: "A execução de pena deve respeitar:", opcoes: ["Princípios constitucionais e legais", "Apenas regulamentos internos", "Critério administrativo", "Nenhum princípio específico"], correta: 0 },
  { pergunta: "A reincidência do preso influencia:", opcoes: ["Progressão de regime e benefícios", "Nada", "Somente multa", "Remição automática"], correta: 0 },
  { pergunta: "O preso pode recorrer de decisões da execução penal através de:", opcoes: ["Tribunais ou juiz da execução", "Somente advogado privado", "Reclamação administrativa", "Nenhuma forma de recurso"], correta: 0 },
  { pergunta: "O direito ao lazer do preso é:", opcoes: ["Previsto para equilíbrio físico e psicológico", "Não previsto", "Opcional", "Somente para regime aberto"], correta: 0 },
  { pergunta: "A assistência pedagógica deve incluir:", opcoes: ["Cursos profissionalizantes e alfabetização", "Apenas cursos teóricos", "Somente leitura de leis", "Não é obrigatória"], correta: 0 },
  { pergunta: "A LEP prevê a reintegração social como:", opcoes: ["Objetivo central da execução penal", "Meta secundária", "Não prevista", "Apenas recomendação"], correta: 0 },
  { pergunta: "O trabalho do preso não pode:", opcoes: ["Ser degradante ou nocivo à saúde", "Ser opcional", "Ser remunerado", "Ser educativo"], correta: 0 },
  { pergunta: "O trabalho do preso é:", opcoes: ["Direito e dever, remunerado", "Opcional e sem remuneração", "Proibido", "Apenas em instituições privadas"], correta: 0 },
  { pergunta: "A pena de multa é aplicável:", opcoes: ["Em substituição ou cumulativamente à privativa de liberdade", "Somente isoladamente", "Nunca", "Apenas para crimes leves"], correta: 0 },
  { pergunta: "O preso deve ser separado de acordo com:", opcoes: ["Idade, sexo e natureza do delito", "Apenas idade", "Somente sexo", "Não há regras de separação"], correta: 0 },
  { pergunta: "O regime semiaberto permite:", opcoes: ["Trabalho externo durante o dia", "Permanência total na unidade", "Saída temporária sem critério", "Sem benefícios de trabalho"], correta: 0 },
  { pergunta: "O auxílio-reclusão é:", opcoes: ["Benefício previdenciário aos dependentes do preso", "Pagamento ao preso", "Multa aplicada ao preso", "Isenção de pena"], correta: 0 },
  { pergunta: "A assistência à saúde do preso deve ser:", opcoes: ["Integral e contínua", "Somente emergencial", "Opcional", "Restrita a hospitais privados"], correta: 0 },
  { pergunta: "O preso tem direito à visita:", opcoes: ["Sim, de acordo com regras da LEP", "Não, salvo decisão judicial", "Somente visitas virtuais", "Somente familiares diretos"], correta: 0 },
  { pergunta: "A execução penal deve considerar:", opcoes: ["O caráter reeducativo e social da pena", "Somente a punição", "A capacidade financeira do preso", "O tipo de crime"], correta: 0 },
  { pergunta: "O condenado a pena de trabalho comunitário deve:", opcoes: ["Cumprir atividades úteis à sociedade", "Ficar em regime fechado", "Ser liberado imediatamente", "Receber multa"], correta: 0 },
  { pergunta: "A assistência jurídica ao preso é:", opcoes: ["Obrigatória, com defensor público se necessário", "Opcional", "Somente privada", "Não prevista"], correta: 0 },
  { pergunta: "O condenado em regime aberto deve:", opcoes: ["Cumprir pena fora da prisão, com regras de conduta", "Ficar totalmente solto", "Cumprir pena dentro da unidade", "Trabalhar apenas à noite"], correta: 0 },
  { pergunta: "O objetivo das penas restritivas de direitos é:", opcoes: ["Alternativa à privativa de liberdade", "Apenas punição simbólica", "Reclusão obrigatória", "Trabalho forçado"], correta: 0 },
  { pergunta: "O preso deve ser informado sobre:", opcoes: ["Seus direitos e deveres", "Somente seu regime de pena", "Nada é informado", "Apenas benefícios"], correta: 0 },
  { pergunta: "O tratamento penal deve ser:", opcoes: ["Individualizado e progressivo", "Padronizado para todos", "Baseado na gravidade do crime apenas", "Totalmente igualitário"], correta: 0 },
  { pergunta: "O direito à educação do preso visa:", opcoes: ["Promover reintegração social", "Somente entretenimento", "Aumentar a pena", "Treinamento profissional apenas"], correta: 0 },
  { pergunta: "O sistema penitenciário deve garantir:", opcoes: ["Segurança, disciplina e tratamento humano", "Somente segurança", "Somente disciplina", "Apenas vigilância externa"], correta: 0 },
  { pergunta: "A pena privativa de liberdade pode ser cumprida:", opcoes: ["Em regimes fechado, semiaberto ou aberto", "Somente fechado", "Somente aberto", "Somente semiaberto"], correta: 0 },
  { pergunta: "O condenado a regime fechado tem direito a:", opcoes: ["Trabalho e educação dentro do presídio", "Trabalho externo", "Liberdade condicional automática", "Saída sem critério"], correta: 0 },
  { pergunta: "A progressão de regime depende de:", opcoes: ["Cumprimento de parte da pena e bom comportamento", "Solicitação do preso", "Decisão automática", "Recomendação da família"], correta: 0 },
  { pergunta: "A execução penal visa:", opcoes: ["Reeducar e reintegrar socialmente o condenado", "Punir sem reintegração", "Somente aplicar a pena", "Controle disciplinar"], correta: 0 },
  { pergunta: "A assistência social ao preso deve:", opcoes: ["Promover reinserção e apoio social", "Não é necessária", "Ser apenas burocrática", "Aplicar multas"], correta: 0 },
  { pergunta: "O condenado que cumpre pena de forma alternativa deve:", opcoes: ["Seguir regras de restrição de direitos", "Ser liberado", "Não tem regras", "Cumprir pena de forma tradicional"], correta: 0 },
  { pergunta: "O Direito Penal tem como função principal:", opcoes: ["Punir delitos e proteger bens jurídicos", "Regular contratos civis", "Administrar bens públicos", "Aplicar multas administrativas"], correta: 0 },
  { pergunta: "O princípio da legalidade significa:", opcoes: ["Não há crime sem lei anterior", "Todos podem criar leis penais", "Crime depende da vontade do juiz", "Lei retroage sempre"], correta: 0 },
  { pergunta: "Crime doloso é aquele em que:", opcoes: ["Há intenção de praticar o delito", "Não há intenção", "Há apenas negligência", "O agente desconhece a lei"], correta: 0 },
  { pergunta: "Crime culposo ocorre quando:", opcoes: ["Há negligência, imprudência ou imperícia", "Há intenção clara", "Não há resultado", "O agente é menor de idade"], correta: 0 },
  { pergunta: "O princípio da proporcionalidade determina que:", opcoes: ["A pena deve ser adequada ao crime", "Todas penas são iguais", "Penas maiores são sempre melhores", "Só vale para crimes patrimoniais"], correta: 0 },
  { pergunta: "O concurso de pessoas ocorre quando:", opcoes: ["Mais de uma pessoa participa do crime", "O crime é cometido sozinho", "O crime é culposo", "Só há vítima"], correta: 0 },
  { pergunta: "A legítima defesa consiste em:", opcoes: ["Reagir a agressão atual e injusta", "Prevenir crime futuro", "Apenas se o agressor estiver armado", "Nunca justifica o uso da força"], correta: 0 },
  { pergunta: "O erro de tipo exclui:", opcoes: ["O dolo do crime", "A culpa", "A necessidade de ação", "A pena de multa"], correta: 0 },
  { pergunta: "O homicídio privilegiado ocorre quando:", opcoes: ["Há circunstâncias que diminuem a pena", "Sempre é punido com reclusão máxima", "Não há vítima", "O crime é culposo"], correta: 0 },
  { pergunta: "O concurso de crimes significa:", opcoes: ["Praticar dois ou mais crimes simultaneamente", "Cometer crime culposo", "Haver apenas crime material", "Aplicar pena alternativa"], correta: 0 },
  { pergunta: "O crime omissivo próprio é aquele em que:", opcoes: ["A omissão é típica e suficiente para o resultado", "A omissão nunca gera crime", "Sempre depende de ação de terceiros", "É culposo"], correta: 0 },
  { pergunta: "O crime omissivo impróprio ocorre quando:", opcoes: ["O agente deveria agir e não age", "A omissão é irrelevante", "Não há crime", "O crime é doloso"], correta: 0 },
  { pergunta: "A tentativa de crime ocorre quando:", opcoes: ["O agente inicia a execução, mas não consuma o delito", "O crime não é iniciado", "A vítima impede o crime com agressão", "O agente se arrepende"], correta: 0 },
  { pergunta: "O arrependimento eficaz é aquele em que:", opcoes: ["O agente impede a consumação do crime", "O agente é punido com aumento de pena", "Só é válido após condenação", "Não há relevância"], correta: 0 },
  { pergunta: "O crime preterdoloso é aquele em que:", opcoes: ["Há dolo no ato e culpa no resultado", "O crime é culposo integral", "O crime é doloso integral", "O agente não pratica ação"], correta: 0 },
  { pergunta: "O dolo eventual ocorre quando:", opcoes: ["O agente assume o risco de produzir o resultado", "Não há intenção", "O agente ignora totalmente o risco", "O crime é culposo"], correta: 0 },
  { pergunta: "A reincidência penal é considerada na:", opcoes: ["Fixação da pena", "Aplicação de multa administrativa", "Determinação de regime de trabalho", "Somente para crimes leves"], correta: 0 },
  { pergunta: "O princípio da humanidade na pena estabelece:", opcoes: ["Proibição de tratamentos cruéis ou degradantes", "Liberdade total do condenado", "Obrigatoriedade de trabalho forçado", "Redução da pena sem limites"], correta: 0 },
  { pergunta: "A legítima defesa putativa ocorre quando:", opcoes: ["O agente acredita estar em perigo injusto", "Houve agressão real", "Não há crime", "O agente é menor de idade"], correta: 0 },
  { pergunta: "O concurso formal de crimes ocorre quando:", opcoes: ["Uma ação resulta em dois ou mais crimes", "Houve apenas um crime", "O crime é culposo", "O crime é impossível"], correta: 0 },
  { pergunta: "O arrependimento posterior aplica-se quando:", opcoes: ["O agente repara voluntariamente o dano após o crime", "O crime é consumado com violência", "Não há vítima", "O crime é culposo"], correta: 0 },
  { pergunta: "O princípio da ofensividade significa:", opcoes: ["Não há crime sem lesão ou perigo concreto", "Todo pensamento é crime", "Crime sempre ocorre em sociedade", "Pena mínima é obrigatória"], correta: 0 },
  { pergunta: "A legítima defesa coletiva é aplicada quando:", opcoes: ["Protege grupo contra agressão atual", "Apenas indivíduos isolados", "Não é prevista no Código Penal", "Só vale para agentes públicos"], correta: 0 },
  { pergunta: "O princípio da insignificância exclui:", opcoes: ["Conduta sem relevância penal", "Todo crime culposo", "Crime doloso grave", "Pena de multa"], correta: 0 },
  { pergunta: "O concurso de agentes primários e reincidentes influencia:", opcoes: ["Regime e pena aplicada", "Nada", "Apenas multa", "Somente advertência"], correta: 0 },
  { pergunta: "O crime omissivo com dever de cuidado envolve:", opcoes: ["Obrigação legal ou contratual de agir", "Não há responsabilidade", "Crime intencional", "Apenas advertência"], correta: 0 },
  { pergunta: "O concurso material ocorre quando:", opcoes: ["Mais de uma ação gera crimes distintos", "Um crime gera múltiplos resultados", "O crime é culposo", "Não há crime"], correta: 0 },
  { pergunta: "O crime impossível ocorre quando:", opcoes: ["O resultado não pode se consumar por meios insuficientes", "Há dolo real", "Sempre há pena", "O agente é absolvido por arrependimento"], correta: 0 },
  { pergunta: "A imputabilidade penal depende de:", opcoes: ["Capacidade de entender o caráter ilícito do fato", "Idade mínima apenas", "Escolaridade", "Nacionalidade"], correta: 0 },
  { pergunta: "O estado de necessidade exclui a ilicitude quando:", opcoes: ["Há perigo atual e inevitável para si ou terceiro", "O crime é doloso", "O agente é reincidente", "Houve arrependimento posterior"], correta: 0 },

]);

